export type HandShape = "open" | "fist" | "point" | "spread" | "flat" | "c_shape" | "pinch" | "v_shape" | "ily" | "hook";

export interface HandPlacement {
  x: number;
  y: number;
  shape: HandShape;
  rotation?: number;
}

export interface ASLWordSign {
  word: string;
  description: string;
  handShape: string;
  movement: string;
  startPosition: string;
  rightHand: HandPlacement;
  leftHand?: HandPlacement;
  arrows?: string;
  twoHanded: boolean;
  category: "greeting" | "common" | "question" | "emotion" | "action" | "pronoun" | "number" | "time" | "misc";
}

export const ASL_WORD_DICTIONARY: Record<string, ASLWordSign> = {
  hello: {
    word: "hello",
    description: "Open hand at forehead, salute outward",
    handShape: "Open flat hand, fingers together",
    movement: "Hand moves away from forehead like a salute",
    startPosition: "Forehead",
    rightHand: { x: 122, y: 28, shape: "open", rotation: -10 },
    arrows: "M 127 28 L 157 20 M 152 15 L 157 20 L 152 25",
    twoHanded: false,
    category: "greeting",
  },
  hi: {
    word: "hi",
    description: "Wave your open hand side to side",
    handShape: "Open hand, fingers spread",
    movement: "Wave side to side at shoulder height",
    startPosition: "Shoulder height",
    rightHand: { x: 168, y: 72, shape: "spread" },
    arrows: "M 158 72 L 178 72 M 174 68 L 178 72 L 174 76",
    twoHanded: false,
    category: "greeting",
  },
  goodbye: {
    word: "goodbye",
    description: "Open and close fingers repeatedly, like waving bye",
    handShape: "Fingers open and close",
    movement: "Fingers flex open and closed",
    startPosition: "Shoulder height",
    rightHand: { x: 162, y: 76, shape: "spread" },
    arrows: "M 152 76 L 172 76 M 168 72 L 172 76 L 168 80",
    twoHanded: false,
    category: "greeting",
  },
  "thank you": {
    word: "thank you",
    description: "Flat hand touches chin then moves forward and down",
    handShape: "Flat hand, fingers together",
    movement: "From chin, move forward and slightly down",
    startPosition: "Chin",
    rightHand: { x: 115, y: 60, shape: "open" },
    arrows: "M 120 62 L 147 78 M 142 73 L 147 78 L 142 83",
    twoHanded: false,
    category: "common",
  },
  thanks: {
    word: "thanks",
    description: "Flat hand touches chin then moves forward",
    handShape: "Flat hand, fingers together",
    movement: "From chin, move forward",
    startPosition: "Chin",
    rightHand: { x: 115, y: 60, shape: "open" },
    arrows: "M 120 60 L 150 52 M 145 47 L 150 52 L 145 57",
    twoHanded: false,
    category: "common",
  },
  please: {
    word: "please",
    description: "Flat hand circles on chest",
    handShape: "Flat hand on chest",
    movement: "Circular motion on chest",
    startPosition: "Chest",
    rightHand: { x: 108, y: 128, shape: "open" },
    arrows: "M 116 128 Q 120 120 112 118 Q 104 120 100 128 Q 100 136 108 136 Q 120 136 116 128",
    twoHanded: false,
    category: "common",
  },
  sorry: {
    word: "sorry",
    description: "Fist circles on chest (like rubbing your heart)",
    handShape: "Closed fist (A handshape)",
    movement: "Circular motion on chest",
    startPosition: "Chest",
    rightHand: { x: 108, y: 128, shape: "fist" },
    arrows: "M 116 128 Q 120 120 112 118 Q 104 120 100 128 Q 100 136 108 136 Q 120 136 116 128",
    twoHanded: false,
    category: "common",
  },
  yes: {
    word: "yes",
    description: "Fist nods up and down (like a nodding head)",
    handShape: "Closed fist (S handshape)",
    movement: "Wrist bends up and down",
    startPosition: "In front of body",
    rightHand: { x: 142, y: 88, shape: "fist" },
    arrows: "M 142 83 L 142 58 M 137 63 L 142 58 L 147 63 M 142 93 L 142 118 M 137 113 L 142 118 L 147 113",
    twoHanded: false,
    category: "common",
  },
  no: {
    word: "no",
    description: "Index and middle finger snap closed to thumb",
    handShape: "Index + middle finger tap to thumb",
    movement: "Fingers snap shut like a beak",
    startPosition: "In front of body",
    rightHand: { x: 130, y: 70, shape: "point" },
    arrows: "M 130 73 L 130 82 M 127 79 L 130 82 L 133 79",
    twoHanded: false,
    category: "common",
  },
  help: {
    word: "help",
    description: "Fist on flat palm, both rise up together",
    handShape: "Thumbs-up fist on open palm",
    movement: "Both hands rise together",
    startPosition: "Waist height",
    rightHand: { x: 108, y: 132, shape: "fist" },
    leftHand: { x: 95, y: 145, shape: "open" },
    arrows: "M 100 127 L 100 97 M 95 102 L 100 97 L 105 102",
    twoHanded: true,
    category: "common",
  },
  water: {
    word: "water",
    description: "W handshape taps chin twice",
    handShape: "W hand (3 fingers spread)",
    movement: "Tap chin twice with index finger",
    startPosition: "Chin",
    rightHand: { x: 118, y: 58, shape: "spread" },
    arrows: "M 118 61 L 118 70 M 115 67 L 118 70 L 121 67",
    twoHanded: false,
    category: "common",
  },
  food: {
    word: "food",
    description: "Bunched fingers tap mouth twice",
    handShape: "All fingertips together (flat O)",
    movement: "Tap near mouth twice",
    startPosition: "Mouth",
    rightHand: { x: 116, y: 50, shape: "pinch" },
    arrows: "M 116 53 L 116 62 M 113 59 L 116 62 L 119 59",
    twoHanded: false,
    category: "common",
  },
  eat: {
    word: "eat",
    description: "Bunched fingers tap mouth repeatedly",
    handShape: "Flat O (fingertips bunched)",
    movement: "Tap mouth repeatedly",
    startPosition: "Mouth",
    rightHand: { x: 116, y: 50, shape: "pinch" },
    arrows: "M 116 53 L 116 62 M 113 59 L 116 62 L 119 59",
    twoHanded: false,
    category: "action",
  },
  drink: {
    word: "drink",
    description: "C hand tilts toward mouth like drinking from cup",
    handShape: "C handshape (like holding a cup)",
    movement: "Tilt toward mouth",
    startPosition: "In front of mouth",
    rightHand: { x: 120, y: 48, shape: "c_shape", rotation: 15 },
    arrows: "M 118 43 L 108 30 M 111 33 L 108 30 L 105 33",
    twoHanded: false,
    category: "action",
  },
  more: {
    word: "more",
    description: "Both hands in flat O, fingertips tap together",
    handShape: "Both hands flat O (bunched fingers)",
    movement: "Fingertips tap together at center",
    startPosition: "In front of chest",
    rightHand: { x: 118, y: 132, shape: "pinch" },
    leftHand: { x: 82, y: 132, shape: "pinch" },
    arrows: "M 118 132 L 93 137 M 98 133 L 93 137 L 98 141 M 82 132 L 107 137 M 102 133 L 107 137 L 102 141",
    twoHanded: true,
    category: "common",
  },
  stop: {
    word: "stop",
    description: "Flat hand chops down onto open palm",
    handShape: "Flat hand strikes down on other palm",
    movement: "Sharp downward chop onto palm",
    startPosition: "In front of body",
    rightHand: { x: 105, y: 128, shape: "flat", rotation: -90 },
    leftHand: { x: 95, y: 142, shape: "open" },
    arrows: "M 105 133 L 105 158 M 100 153 L 105 158 L 110 153",
    twoHanded: true,
    category: "action",
  },
  want: {
    word: "want",
    description: "Both hands open, palms up, pull toward body",
    handShape: "Open clawed hands, pull inward",
    movement: "Pull hands toward body while closing fingers",
    startPosition: "In front of body",
    rightHand: { x: 135, y: 125, shape: "spread", rotation: 15 },
    leftHand: { x: 65, y: 125, shape: "spread", rotation: -15 },
    arrows: "M 135 125 L 110 130 M 115 126 L 110 130 L 115 134 M 65 125 L 90 130 M 85 126 L 90 130 L 85 134",
    twoHanded: true,
    category: "common",
  },
  need: {
    word: "need",
    description: "Bent index finger (X hand) bends downward",
    handShape: "Bent index finger (X handshape)",
    movement: "Wrist bends downward",
    startPosition: "In front of body",
    rightHand: { x: 135, y: 115, shape: "point" },
    arrows: "M 135 120 L 135 145 M 130 140 L 135 145 L 140 140",
    twoHanded: false,
    category: "common",
  },
  good: {
    word: "good",
    description: "Flat hand at chin moves down to open palm",
    handShape: "Flat hand from chin",
    movement: "Hand drops from chin forward and down",
    startPosition: "Chin",
    rightHand: { x: 115, y: 60, shape: "open" },
    arrows: "M 120 62 L 147 78 M 142 73 L 147 78 L 142 83",
    twoHanded: false,
    category: "common",
  },
  bad: {
    word: "bad",
    description: "Flat hand at chin, flip down (palm faces down)",
    handShape: "Flat hand flips from chin",
    movement: "Hand turns over moving away from chin",
    startPosition: "Chin",
    rightHand: { x: 115, y: 62, shape: "open", rotation: 180 },
    arrows: "M 115 67 L 115 92 M 110 87 L 115 92 L 120 87",
    twoHanded: false,
    category: "common",
  },
  love: {
    word: "love",
    description: "Cross both arms over chest, fists closed",
    handShape: "Both fists crossed on chest",
    movement: "Arms cross and hug chest",
    startPosition: "Chest",
    rightHand: { x: 78, y: 128, shape: "fist" },
    leftHand: { x: 122, y: 128, shape: "fist" },
    twoHanded: true,
    category: "emotion",
  },
  happy: {
    word: "happy",
    description: "Flat hand brushes up on chest twice",
    handShape: "Open flat hand",
    movement: "Brush upward on chest, twice",
    startPosition: "Chest",
    rightHand: { x: 112, y: 118, shape: "open" },
    arrows: "M 112 113 L 112 83 M 107 88 L 112 83 L 117 88",
    twoHanded: false,
    category: "emotion",
  },
  sad: {
    word: "sad",
    description: "Open hands move down in front of face",
    handShape: "Open hands, fingers spread",
    movement: "Hands slide down from face",
    startPosition: "Face",
    rightHand: { x: 115, y: 40, shape: "spread" },
    arrows: "M 115 45 L 115 70 M 110 65 L 115 70 L 120 65",
    twoHanded: false,
    category: "emotion",
  },
  angry: {
    word: "angry",
    description: "Claw hand from face moves outward",
    handShape: "Spread/claw hand",
    movement: "Hand pulls away from face outward",
    startPosition: "Face",
    rightHand: { x: 118, y: 42, shape: "spread" },
    arrows: "M 123 42 L 153 34 M 148 29 L 153 34 L 148 39",
    twoHanded: false,
    category: "emotion",
  },
  understand: {
    word: "understand",
    description: "Fist at forehead, then index finger flicks up",
    handShape: "Fist near temple, index flicks up",
    movement: "Index finger springs upward",
    startPosition: "Temple/forehead",
    rightHand: { x: 122, y: 26, shape: "point" },
    arrows: "M 122 21 L 122 -4 M 117 1 L 122 -4 L 127 1",
    twoHanded: false,
    category: "common",
  },
  "don't understand": {
    word: "don't understand",
    description: "Touch forehead and shake finger side to side",
    handShape: "Index at temple, shakes",
    movement: "Finger shakes side to side at forehead",
    startPosition: "Temple",
    rightHand: { x: 122, y: 26, shape: "point" },
    arrows: "M 112 26 L 132 26 M 128 22 L 132 26 L 128 30",
    twoHanded: false,
    category: "common",
  },
  name: {
    word: "name",
    description: "H handshape (two fingers) taps on other H handshape",
    handShape: "Two extended fingers (H hand)",
    movement: "Cross-tap the fingers",
    startPosition: "In front of body",
    rightHand: { x: 118, y: 120, shape: "v_shape", rotation: -90 },
    leftHand: { x: 90, y: 130, shape: "v_shape", rotation: -90 },
    arrows: "M 118 123 L 118 132 M 115 129 L 118 132 L 121 129",
    twoHanded: true,
    category: "common",
  },
  what: {
    word: "what",
    description: "Open hands, palms up, shake side to side",
    handShape: "Open palms facing up",
    movement: "Shake hands side to side",
    startPosition: "In front of body",
    rightHand: { x: 145, y: 138, shape: "open", rotation: 180 },
    leftHand: { x: 55, y: 138, shape: "open", rotation: 180 },
    arrows: "M 145 138 L 160 138 M 156 134 L 160 138 L 156 142 M 55 138 L 40 138 M 44 134 L 40 138 L 44 142",
    twoHanded: true,
    category: "question",
  },
  where: {
    word: "where",
    description: "Index finger waves side to side",
    handShape: "Index finger pointing up",
    movement: "Wave finger side to side",
    startPosition: "In front of body",
    rightHand: { x: 148, y: 98, shape: "point" },
    arrows: "M 138 98 L 158 98 M 154 94 L 158 98 L 154 102",
    twoHanded: false,
    category: "question",
  },
  when: {
    word: "when",
    description: "Index finger circles around other index finger",
    handShape: "Both index fingers extended",
    movement: "One circles then touches the other",
    startPosition: "In front of body",
    rightHand: { x: 142, y: 98, shape: "point" },
    arrows: "M 150 98 Q 154 90 146 88 Q 138 90 134 98 Q 134 106 142 106 Q 154 106 150 98",
    twoHanded: false,
    category: "question",
  },
  why: {
    word: "why",
    description: "Touch forehead, pull hand away",
    handShape: "Middle finger touches forehead, then Y hand",
    movement: "From forehead, pull away",
    startPosition: "Forehead",
    rightHand: { x: 122, y: 28, shape: "point" },
    arrows: "M 127 28 L 157 20 M 152 15 L 157 20 L 152 25",
    twoHanded: false,
    category: "question",
  },
  who: {
    word: "who",
    description: "Index finger circles near mouth/chin",
    handShape: "L handshape with index at lips",
    movement: "Index finger circles in front of chin",
    startPosition: "Chin",
    rightHand: { x: 115, y: 60, shape: "point" },
    arrows: "M 123 60 Q 127 52 119 50 Q 111 52 107 60 Q 107 68 115 68 Q 127 68 123 60",
    twoHanded: false,
    category: "question",
  },
  how: {
    word: "how",
    description: "Both fists knuckles together, roll outward to open",
    handShape: "Fists roll open into palms-up",
    movement: "Roll hands open and outward",
    startPosition: "In front of body",
    rightHand: { x: 118, y: 125, shape: "fist" },
    leftHand: { x: 82, y: 125, shape: "fist" },
    arrows: "M 123 125 L 148 130 M 143 126 L 148 130 L 143 134 M 77 125 L 52 130 M 57 126 L 52 130 L 57 134",
    twoHanded: true,
    category: "question",
  },
  i: {
    word: "i",
    description: "Point to yourself with index finger",
    handShape: "Index finger pointing at chest",
    movement: "Point to center of chest",
    startPosition: "Chest",
    rightHand: { x: 108, y: 128, shape: "point" },
    twoHanded: false,
    category: "pronoun",
  },
  me: {
    word: "me",
    description: "Point to yourself with index finger",
    handShape: "Index finger pointing at chest",
    movement: "Point to center of chest",
    startPosition: "Chest",
    rightHand: { x: 108, y: 128, shape: "point" },
    twoHanded: false,
    category: "pronoun",
  },
  you: {
    word: "you",
    description: "Point index finger at the other person",
    handShape: "Index finger pointing forward",
    movement: "Point toward listener",
    startPosition: "In front of body",
    rightHand: { x: 155, y: 105, shape: "point" },
    twoHanded: false,
    category: "pronoun",
  },
  we: {
    word: "we",
    description: "Index finger points to one shoulder then arcs to the other",
    handShape: "Index finger extended",
    movement: "Arc from one shoulder to the other",
    startPosition: "Shoulder",
    rightHand: { x: 115, y: 118, shape: "point" },
    arrows: "M 105 118 L 135 118 M 131 114 L 135 118 L 131 122",
    twoHanded: false,
    category: "pronoun",
  },
  they: {
    word: "they",
    description: "Point to side and sweep outward",
    handShape: "Index finger extended",
    movement: "Point outward and sweep to the side",
    startPosition: "Side of body",
    rightHand: { x: 168, y: 98, shape: "point" },
    arrows: "M 168 98 L 193 103 M 188 99 L 193 103 L 188 107",
    twoHanded: false,
    category: "pronoun",
  },
  my: {
    word: "my",
    description: "Open palm placed on chest",
    handShape: "Open flat palm on chest",
    movement: "Touch chest with open palm",
    startPosition: "Chest",
    rightHand: { x: 108, y: 128, shape: "open" },
    twoHanded: false,
    category: "pronoun",
  },
  mine: {
    word: "mine",
    description: "Open palm placed on chest",
    handShape: "Open flat palm on chest",
    movement: "Touch chest with open palm",
    startPosition: "Chest",
    rightHand: { x: 108, y: 128, shape: "open" },
    twoHanded: false,
    category: "pronoun",
  },
  friend: {
    word: "friend",
    description: "Hook index fingers together",
    handShape: "Hooked index fingers linked",
    movement: "Index fingers hook and unhook",
    startPosition: "In front of chest",
    rightHand: { x: 112, y: 128, shape: "hook" },
    leftHand: { x: 92, y: 138, shape: "hook", rotation: 180 },
    arrows: "M 112 131 L 112 140 M 109 137 L 112 140 L 115 137",
    twoHanded: true,
    category: "misc",
  },
  family: {
    word: "family",
    description: "Both pinched hands circle around in front of body",
    handShape: "F handshape (pinched fingers)",
    movement: "Both hands circle outward",
    startPosition: "In front of upper chest",
    rightHand: { x: 135, y: 108, shape: "pinch" },
    leftHand: { x: 65, y: 108, shape: "pinch" },
    arrows: "M 143 108 Q 147 100 139 98 Q 131 100 127 108 Q 127 116 135 116 Q 147 116 143 108 M 57 108 Q 53 100 61 98 Q 69 100 73 108 Q 73 116 65 116 Q 53 116 57 108",
    twoHanded: true,
    category: "misc",
  },
  school: {
    word: "school",
    description: "Clap hands together twice",
    handShape: "Open flat hands clapping",
    movement: "Hands clap together",
    startPosition: "In front of chest",
    rightHand: { x: 115, y: 125, shape: "open", rotation: -90 },
    leftHand: { x: 85, y: 138, shape: "open" },
    arrows: "M 115 128 L 115 137 M 112 134 L 115 137 L 118 134",
    twoHanded: true,
    category: "misc",
  },
  work: {
    word: "work",
    description: "Right fist taps left fist on top",
    handShape: "Both fists, right taps left",
    movement: "Right fist taps down on left fist",
    startPosition: "In front of body",
    rightHand: { x: 115, y: 125, shape: "fist" },
    leftHand: { x: 90, y: 138, shape: "fist" },
    arrows: "M 115 128 L 115 137 M 112 134 L 115 137 L 118 134",
    twoHanded: true,
    category: "action",
  },
  home: {
    word: "home",
    description: "Pinched hand from chin to cheek",
    handShape: "Flat O (pinched fingers)",
    movement: "Touch chin then move to cheek",
    startPosition: "Chin",
    rightHand: { x: 118, y: 50, shape: "pinch" },
    arrows: "M 115 55 L 122 45 M 119 48 L 122 45 L 125 48",
    twoHanded: false,
    category: "misc",
  },
  come: {
    word: "come",
    description: "Index finger beckons toward you",
    handShape: "Index finger extended, curling inward",
    movement: "Finger curls toward body repeatedly",
    startPosition: "In front of body",
    rightHand: { x: 148, y: 118, shape: "point", rotation: 180 },
    arrows: "M 148 118 L 123 123 M 128 119 L 123 123 L 128 127",
    twoHanded: false,
    category: "action",
  },
  go: {
    word: "go",
    description: "Both index fingers point forward and move ahead",
    handShape: "Both index fingers extended",
    movement: "Both arc forward",
    startPosition: "In front of body",
    rightHand: { x: 138, y: 108, shape: "point" },
    leftHand: { x: 75, y: 108, shape: "point" },
    arrows: "M 143 108 L 173 100 M 168 95 L 173 100 L 168 105 M 80 108 L 110 100 M 105 95 L 110 100 L 105 105",
    twoHanded: true,
    category: "action",
  },
  see: {
    word: "see",
    description: "V hand from eyes moves forward",
    handShape: "V handshape (two fingers)",
    movement: "Hand moves forward from eyes",
    startPosition: "Eyes",
    rightHand: { x: 122, y: 36, shape: "v_shape" },
    arrows: "M 127 36 L 157 28 M 152 23 L 157 28 L 152 33",
    twoHanded: false,
    category: "action",
  },
  look: {
    word: "look",
    description: "V hand from eyes moves forward",
    handShape: "V handshape (two fingers)",
    movement: "Hand moves forward from eyes",
    startPosition: "Eyes",
    rightHand: { x: 122, y: 36, shape: "v_shape" },
    arrows: "M 127 36 L 157 28 M 152 23 L 157 28 L 152 33",
    twoHanded: false,
    category: "action",
  },
  know: {
    word: "know",
    description: "Flat hand taps forehead",
    handShape: "Flat open hand at forehead",
    movement: "Tap forehead with fingertips",
    startPosition: "Forehead",
    rightHand: { x: 122, y: 26, shape: "open" },
    arrows: "M 122 29 L 122 38 M 119 35 L 122 38 L 125 35",
    twoHanded: false,
    category: "action",
  },
  think: {
    word: "think",
    description: "Point at forehead",
    handShape: "Index finger at forehead",
    movement: "Touch forehead with index finger",
    startPosition: "Forehead",
    rightHand: { x: 118, y: 26, shape: "point" },
    twoHanded: false,
    category: "action",
  },
  learn: {
    word: "learn",
    description: "Pull from open palm up to forehead",
    handShape: "Open hand pulls knowledge from palm to head",
    movement: "Hand moves from palm upward to forehead",
    startPosition: "In front of body to forehead",
    rightHand: { x: 112, y: 28, shape: "open" },
    leftHand: { x: 88, y: 138, shape: "open" },
    arrows: "M 100 133 L 100 38 M 95 43 L 100 38 L 105 43",
    twoHanded: true,
    category: "action",
  },
  sleep: {
    word: "sleep",
    description: "Spread hand over face, closing downward",
    handShape: "Spread hand closing over face",
    movement: "Hand slides down face, fingers close",
    startPosition: "Face",
    rightHand: { x: 110, y: 38, shape: "spread" },
    arrows: "M 110 43 L 110 68 M 105 63 L 110 68 L 115 63",
    twoHanded: false,
    category: "action",
  },
  "i love you": {
    word: "i love you",
    description: "Thumb, index finger, and pinky extended (ILY sign)",
    handShape: "Thumb + index + pinky out, middle + ring closed",
    movement: "Hold steady",
    startPosition: "In front of body",
    rightHand: { x: 145, y: 105, shape: "ily" },
    twoHanded: false,
    category: "emotion",
  },
};

const PHRASE_MAP: Record<string, string> = {
  "thank you": "thank you",
  "don't understand": "don't understand",
  "i love you": "i love you",
};

export function parseTextToSignWords(text: string): Array<{ word: string; sign: ASLWordSign | null }> {
  const normalized = text.toLowerCase().trim();
  const result: Array<{ word: string; sign: ASLWordSign | null }> = [];
  const words = normalized.split(/\s+/);
  let i = 0;
  while (i < words.length) {
    let matched = false;
    for (let len = 3; len >= 2; len--) {
      if (i + len <= words.length) {
        const phrase = words.slice(i, i + len).join(" ");
        if (PHRASE_MAP[phrase]) {
          const sign = ASL_WORD_DICTIONARY[PHRASE_MAP[phrase]] || null;
          result.push({ word: phrase, sign });
          i += len;
          matched = true;
          break;
        }
      }
    }
    if (!matched) {
      const w = words[i];
      const cleaned = w.replace(/[^a-z']/g, "");
      if (cleaned) {
        const sign = ASL_WORD_DICTIONARY[cleaned] || null;
        result.push({ word: cleaned, sign });
      }
      i++;
    }
  }
  return result;
}
